### ISSUE TITLE
RDF generation from RxNav search/RxNorm relation prediction

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/med_mapping#15]
Right now, script `rxnav_med_mapping_pds_proximity_classifier.R` in this medication mapping repo creates a CSV file output, where each row is a classified search result. To be useful in the TURBO cohort explorer, the CSV needs to be instantiated into RDF.

## Workflow with established and new steps
1. a medication string was taken from some EHR-like source
1. the medication string was submitted to the RxNav approximate search
1. the search returns predicted RxCUIs along with scores and ranks
1. metadata (source, type, etc.) are obtained for the predicted RxCUIS
1. additional training features like string similarities are generated
1. a previously trained random forest is used to classify each search result as exactly right ("identical"), removed from the latent truth by one well-characterized RxNorm relation, or "more distant"
1. NEW: the rows are culled so that only most useful prediction(s) for each medication string are retained and the others are discarded. (needs elaboration)
1. NEW: the columns are rearranged to reflect the temporality of the search and classify process, and a few less-useful columns are removed 

## Related issues
See also #14. This repo's readme has been revised based on comments from and @hjwilli.

- [ ] #16 : Impact of structural differences between new RDF and existing RDF in `med_map_support_20180403_boosted_20190426`
- [ ] #17 : `ODS` schema from Penn's clinical data warehouse no longer utilized
- [ ] #18 : It appears that primary keys and `FULL_NAME`s from `MDM.R_MEDICATION` are stable over time, so PKs can be used as unique identifiers. This will improve integration and generalizability opportunities.
- [ ] #19 : Current significance of non-printing characters in `R_MEDICATION.FULL_NAME`s
- [ ] #20 : Would need new links between RxCUI-identified meds and OBO classes/roles
- [ ] #21 : CURL link between newest R med mapping scripts and RxNav Container lost after ~ 10k approximate match searches
- [ ] #22 : Generalize current medication mapping workflow for relevance to inputs other than "PDS" 
- [ ] #23 : Create properties/predicates in TURBO Ontology for medication mapping model? 
- [ ] #24 : Mechanism for RDF-instantiation of current medication mapping CSV output
